modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = "Huge thanks to Itsuka and Player2 team"
description = '''${mod_description}'''

[[mixins]]
config = "mindofthecolony.mixins.json"

[[mixins]]
config = "mindofthecolony-generated.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecolonies"
type = "required"
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"
