plugins {
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.github.javaparser:javaparser-core:3.26.4'
}

gradlePlugin {
    plugins {
        mixinGenerator {
            id = 'mindofthecolony.mixin-generator'
            implementationClass = 'com.goodbird.buildtools.MixinGeneratorPlugin'
        }
    }
}
